apiVersion: v2
name: mailer
description: A Helm chart for deploying the mailer service
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/hasAnybodySeenHarry/mailer
sources:
  - https://github.com/hasAnybodySeenHarry/mailer
