replicaCount: 1

image:
  registry: docker.io
  repository: ""
  tag: ""
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

serviceAccountName: default

deploymentAnnotations: {}
podAnnotations: {}

podSecurityContext: {}

serviceAccount:
  create: false
  name: ""

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: false
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: []

extraEnv: []

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

env:
- name: AMQP_USERNAME
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: username
- name: AMQP_PASSWORD
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: password
- name: AMQP_HOST
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: host
- name: AMQP_PORT
  valueFrom:
    secretKeyRef:
      name: rabbitmq-secrets
      key: port
- name: MAIL_API_KEY
  value: some-key
- name: MAIL_DOMAIN
  value: some-domain
- name: ENV
  value: development