apiVersion: v1
kind: Service
metadata:
  labels:
    app: mailer
  name: mailer
  namespace: default
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mailer
  type: ClusterIP